version: 2.1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-server:
          filters:
            tags:
              only: /.*/
      - build-client:
          filters:
            tags:
              only: /.*/
      - publish-images:
          filters:
            tags:
              only: /.*/
            branches:
              only: master
          requires:
            - build-server
            - build-client

jobs:
  build-server:
    working_directory: ~/chat-app/server # All the steps below are being run in the server directory
    docker:
      - image: circleci/node:lts
      - image: postgres:11.4-alpine
        environment:
          POSTGRES_PASSWORD: testpassword
          POSTGRES_USER: testuser
          POSTGRES_DB: whatsapp
    steps:
      - checkout:
          path: ~/chat-app
      - run:
          name: install-dependencies
          command: yarn install
      - run:
          name: compile server typescript code
          command: yarn build
      - run:
          name: run server tests
          command: yarn test -u
      - store_test_results:
          path: test-results
      - run:
          name: run tslint
          command: yarn lint

  build-client:
    working_directory: ~/chat-app/client # All the steps below are being run in the client directory
    docker:
      - image: circleci/node:lts
    steps:
      - checkout:
          path: ~/chat-app
      - run:
          name: install-dependencies
          command: yarn install
      - run:
          name: run codegen
          command: yarn codegen
      - run:
          name: compile server typescript code
          command: yarn build
      - run:
          name: run server tests
          command: yarn test -u
      - store_test_results:
          path: test-results

  publish-images:
    working_directory: ~/chat-app/client # All the steps below are being run in the client directory
    docker:
      # image for building docker containers
      - image: docker:17.12.1-ce-git
    steps:
      - checkout:
          path: ~/chat-app
      - run: |
          cd server          
          TAG=$CIRCLE_TAG ./scripts/buildContainer.sh
          TAG=$CIRCLE_TAG ./scripts/publishContainer.sh
      - run: |
          cd client          
          TAG=$CIRCLE_TAG ./scripts/buildContainer.sh
          TAG=$CIRCLE_TAG ./scripts/publishContainer.sh
      